version: "3.7"
services:
  xz-middleware:
    image: yijun9124/xz-service-middleware
    depends_on:
      - xz-db
      - mqtt-broker
    ports:
      - "7667:7667"
    environment:
      - LOCALHOST
      - DB_HOST
      - DB_PORT
      - MQTT_HOST
      - CONTROLLER_URL
      - MIDDLEWARE_URL
    restart: always
  cranemagic-web:
    image: yijun9124/cranemagic-service-webapi
    depends_on:
      - xz-db
      - mqtt-broker
    ports:
      - "6776:6776"
    environment:
      - LOCALHOST
      - DB_HOST
      - DB_PORT
      - MQTT_HOST
      - CONTROLLER_URL
      - MIDDLEWARE_URL
    restart: always
  cranemagic-mqtt:
    image: yijun9124/cranemagic-service-mqtt
    depends_on:
      - xz-db
      - mqtt-broker
    environment:
      - LOCALHOST
      - DB_HOST
      - DB_PORT
      - MQTT_HOST
      - CONTROLLER_URL
      - MIDDLEWARE_URL
    restart: always
  cranemagic-frontend-nginx:
    image: yijun9124/cranemagic-frontend-wms-nginx
    depends_on:
      - xz-db
      - mqtt-broker
    ports:
      - "80:80"
    restart: always
  mqtt-broker:
    image: yijun9124/cranemagic-mosquitto
    ports:
      - "1883:1883"
      - "1884:1884"
      - "8083:8083"
      - "8084:8084"
    restart: always
  xz-db:
    image: yijun9124/xz-database
    ports:
      - "6612:3306"
    environment:
      - MYSQL_ROOT_PASSWORD
    restart: always
    volumes:
      - ./data:/var/lib/mysql
  
  cranemagic_tcp:
    image: yijun9124/cranemagic-servers-tcp
    container_name: cranemagic_tcp
    ports:
      - "5024:5024"
  cranemagic_udp:
    image: yijun9124/cranemagic-servers-udp
    container_name: cranemagic_udp
    ports:
      - "5025:5025/udp"
